[build]
  base = "/frontend"
  command = "npm run build"
  publish = "frontend/dist"  # Ensure this is the correct path where Vite outputs the build files

[functions]
  directory = "frontend/netlify-functions"  # Ensure this is the correct path to your Netlify functions
