[build]
  base = "/frontend"
  command = "npm run build"
  publish = "frontend/dist"  # Adjust this to your build output directory

[functions]
  directory = "frontend/netlify-functions"  # Ensure this path is correct
