[build]
  base = "/frontend"
  command = "npm run build"
  publish = "dist"  # This should be the output directory from Vite's build

[functions]
  directory = "netlify-functions"  # This should be relative to the root of the project
